version: 2.1

jobs:
  test:
    docker:
<<<<<<< HEAD
      - image: circleci/php:7.4.7-node
      - image: circleci/mysql:latest
        command: [--default-authentication-plugin=mysql_native_password]
    working_directory: ~/repo
    resource_class: large
    environment:
      - WP_TESTS_DIR: '/tmp/wordpress-tests-lib'
      - WP_CORE_DIR: '/tmp/wordpress/'
    steps:
      - checkout
      - run:
          name: 'Setup Environment Variables'
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Run tests
          command: |
            scripts/setup.sh && \
=======
      - image: circleci/7.4.7-node
    working_directory: ~/repo
    resource_class: large
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
>>>>>>> update for builds in circle ci
            scripts/test.sh

  build:
    docker:
      - image: circleci/php:7.4.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run build locally
          command: |
            scripts/build.sh

workflows:
  version: 2
<<<<<<< HEAD
  build_release:
    jobs:
      - test:
          context: build
          filters:
            tags:
              only: /.*/
=======
  deploy_plugin:
    jobs:
      - test:
          context: build
      - build:
          context: build
          filters:
            tags:
              only: /.*/
            branches:
              ignore:
                - production
>>>>>>> update for builds in circle ci

      - deploy-prod-approval:
          type: approval
          name: deploy-prod-approval
          requires:
<<<<<<< HEAD
            - test
=======
            - docker-build-push
>>>>>>> update for builds in circle ci
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

<<<<<<< HEAD
      - build:
          name: deploy-prod
          context: prod
=======
      - deploy:
          name: deploy-prod
          context: prod
          environment: prod_oregon
>>>>>>> update for builds in circle ci
          requires:
            - deploy-prod-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
