version: 2.1

jobs:
  test:
    docker:
      - image: circleci/php:7.4.7-node
      - image: circleci/mysql:latest
        command: [--default-authentication-plugin=mysql_native_password]
    working_directory: ~/repo
    resource_class: large
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run:
          name: "Setup Environment Variables"
          command: |
            echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
            source /home/circleci/.bashrc
      - run:
          name: Run tests
          command: |
            scripts/setup.sh && \
            scripts/test.sh

  build:
    docker:
      - image: circleci/php:7.4.7-node
      - image: circleci/mysql:latest
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run build locally
          command: |
            scripts/build.sh

workflows:
  version: 2
  build_release:
    jobs:
      - test:
          context: build

      # - deploy-prod-approval:
      #     type: approval
      #     name: deploy-prod-approval
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/

      - build:
          name: deploy-prod
          context: prod
          # requires:
          #   - deploy-prod-approval
          # filters:
          #   branches:
          #     ignore: /.*/
          #   tags:
          #     only: /^v.*/
