version: 2.1

jobs:
  test:
    docker:
      - image: circleci/7.4.7-node
    working_directory: ~/repo
    resource_class: large
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            scripts/test.sh

  build:
    docker:
      - image: circleci/php:7.4.7-node
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run build locally
          command: |
            scripts/build.sh

workflows:
  version: 2
  build_release:
    jobs:
      - test:
          context: build

      - deploy-prod-approval:
          type: approval
          name: deploy-prod-approval
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - build:
          name: deploy-prod
          context: prod
          requires:
            - deploy-prod-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
