const latestVideosFixture = {
  data: {
    videoSet: {
      totalCount: 3636,
      pageResults: [
        {
          id: '3641',
          title: "Beware of the economy's 'last mile': advisor",
          description: "Summit Place Financial's Liz Miller says the markets are rising now on increasingly stronger economic data. But she tells Reuters' Fred Katayama that longer term, the economic recovery could plateau as businesses fail and some workers become permanently unemployed.",
          summary: "Summit Place Financial's Liz Miller says the markets are rising now on increasingly stronger economic data. But she tells Reuters' Fred Katayama that longer term, the economic recovery could plateau as businesses fail and some workers become permanently unemployed.",
          tags: [
            'building permits',
            'communications stocks',
            'economic recovery',
            'economy',
            'election',
            'fred katayama',
            'housing starts',
            'last mile',
            'liz miller',
            'stocks',
            'tech stocks',
            'unemployment',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/db2984fe-2421-43ed-b459-762084c4eede.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165037528001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '11',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'Business',
          ],
          duration: 323,
          created: '2020-06-17T19:32:01.486118+00:00',
          modified: '2020-06-17T19:35:45.593596+00:00',
          activatedAt: '2020-06-17T19:35:45.596745+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRKVPN',
        },
        {
          id: '3640',
          title: 'WHO sees "green shoots" of hope in pandemic',
          description: 'Signs of hope have started to show in the fight against the COVID-19 pandemic, the World Health Organization (WHO) said on Wednesday, but it added that countries must continue to work on prevention measures to limit the spread of the new coronavirus.',
          summary: 'Signs of hope have started to show in the fight against the COVID-19 pandemic, the World Health Organization (WHO) said on Wednesday, but it added that countries must continue to work on prevention measures to limit the spread of the new coronavirus.',
          tags: [
            'coronavirus',
            'covid 19',
            'green shoots',
            'who',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/302c8a01-8943-48f2-8f91-d5c255bb086c.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165030615001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 49,
          created: '2020-06-17T18:45:55.107522+00:00',
          modified: '2020-06-17T18:47:07.487231+00:00',
          activatedAt: '2020-06-17T18:47:07.487842+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRL7I9',
        },
        {
          id: '3639',
          title: 'All you need to know from the June 17 coronavirus briefing',
          description: "A round-up of the Government's daily Covid-19 press conference, where Culture Secretary Oliver Dowden said the return of the Premier League paves the way for the opening of other entertainment venues.",
          summary: "A round-up of the Government's daily Covid-19 press conference, where Culture Secretary Oliver Dowden said the return of the Premier League paves the way for the opening of other entertainment venues.",
          tags: [
            'coronavirus',
            'covid 19',
            'culture secretary',
            'daily briefing',
            'downing street',
            'entertainment',
            'lockdown',
            'oliver dowden',
            'politics',
            'premier league',
            'statue',
            'winston churchill',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/12/9bb0f8f3-f079-46b8-8751-879548c25143.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165025805001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '4',
            provider: {
              id: '12',
              name: 'Press Association',
              legalName: 'Press Association',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/12/de19d53d-c02f-4fe3-ad55-9a5b1f48ecfc.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 108,
          created: '2020-06-17T18:33:52.026515+00:00',
          modified: '2020-06-17T18:35:19.949546+00:00',
          activatedAt: '2020-06-17T18:35:19.949475+00:00',
          providerAssetId: '80669',
        },
        {
          id: '3638',
          title: "'You have the power to help us' -George Floyd's brother to the U.N.",
          description: 'The brother of the late George Floyd, Philonise Floyd, called on the top United Nations human rights body on Wednesday to investigate police brutality and racial discrimination in the United States.',
          summary: 'The brother of the late George Floyd, Philonise Floyd, called on the top United Nations human rights body on Wednesday to investigate police brutality and racial discrimination in the United States.',
          tags: [
            'george floyd',
            'philonise floyd',
            'un',
            'united nations',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/33f4127b-9866-4fd0-9e2f-93a251010e53.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165026561001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 122,
          created: '2020-06-17T18:28:51.683279+00:00',
          modified: '2020-06-17T18:30:31.114256+00:00',
          activatedAt: '2020-06-17T18:30:31.113721+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRL97J',
        },
        {
          id: '3637',
          title: 'History of protest in America',
          description: 'Across history, protest has shaped societies in monumental ways,  it has been an age-old method for the public to air their outrage in a public forum  moving on mass to make clear their views are echoed by many.  Activism in the United states has helped catalyse monumental change in laws and social perception. Here we will explore some of the pivotal people and movements that changed the world as we know it.',
          summary: 'Across history, protest has shaped societies in monumental ways,  it has been an age-old method for the public to air their outrage in a public forum  moving on mass to make clear their views are echoed by many.  Activism in the United states has helped catalyse monumental change in laws and social perception. Here we will explore some of the pivotal people and movements that changed the world as we know it.',
          tags: [
            'activism',
            'battle of seattle',
            'black live matter',
            'equal pay',
            'equal rights',
            'george floyd',
            'martin luther king',
            'occupy wall street',
            'protest',
            'usa',
            'vietnam war',
            'womens march',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/1/badda35d-8a6b-410e-a65e-d81dcd5d66bd.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165024685001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '8',
            provider: {
              id: '1',
              name: 'Oovvuu',
              legalName: 'Oovvuu Pty Ltd',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/1/dab1fd03-7b87-4944-9e3b-793083378f85.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 250,
          created: '2020-06-17T18:20:49.464239+00:00',
          modified: '2020-06-17T18:24:46.242863+00:00',
          activatedAt: '2020-06-17T18:24:46.242236+00:00',
          providerAssetId: '80660',
        },
        {
          id: '3636',
          title: "Bars closed, Mexican musicians bring 'joy' to the home",
          description: 'With cantinas and bars shut and private events with live music practically non-existent, Mexican street musician Efrain Giron and his troop have adapted to bring a little "joy" outside homes in Mexico City.',
          summary: 'With cantinas and bars shut and private events with live music practically non-existent, Mexican street musician Efrain Giron and his troop have adapted to bring a little "joy" outside homes in Mexico City.',
          tags: [
            'bars',
            'cantinas',
            'closed',
            'coronavirus',
            'home',
            'marimba',
            'mexico city',
            'mexico musicians',
            'music',
            'performers',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/7d611e50-9ef3-497d-a35e-fbdbf99d3414.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165021670001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 72,
          created: '2020-06-17T18:13:53.035829+00:00',
          modified: '2020-06-17T18:17:50.987547+00:00',
          activatedAt: '2020-06-17T18:15:29.568722+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRKTB5',
        },
        {
          id: '3635',
          title: 'Biden opens up 13-point lead over Trump: poll',
          description: '[NFA] Democratic presidential candidate Joe Biden has opened up a 13-point lead over President Donald Trump - the widest margin this year - according to the latest Reuters/Ipsos poll as Americans grow more critical of Trump over his handling of the coronavirus pandemic and protests against police brutality. Colette Luke has more.',
          summary: '[NFA] Democratic presidential candidate Joe Biden has opened up a 13-point lead over President Donald Trump - the widest margin this year - according to the latest Reuters/Ipsos poll as Americans grow more critical of Trump over his handling of the coronavirus pandemic and protests against police brutality. Colette Luke has more.',
          tags: [
            '2020 election',
            'biden lead',
            'biden poll trump',
            'joe biden',
            'reuters poll',
            'trump biden',
            'trump reelection',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/f373e353-7989-4f63-b70d-7a350a3ac337.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165022642001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 126,
          created: '2020-06-17T18:02:54.822199+00:00',
          modified: '2020-06-17T18:04:54.719076+00:00',
          activatedAt: '2020-06-17T18:04:54.718333+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRL8F3',
        },
        {
          id: '3626',
          title: 'Get ready for no-deal Brexit, Germany warns EU',
          description: "Berlin is warning other EU members to prepare for a no-deal Brexit, believing positions are far apart and time too short for an agreement. That's according to an internal government document seen by Reuters. Lucy Fielder reports.",
          summary: "Berlin is warning other EU members to prepare for a no-deal Brexit, believing positions are far apart and time too short for an agreement. That's according to an internal government document seen by Reuters. Lucy Fielder reports.",
          tags: [
            'boris johnson',
            'brexit',
            'european union',
            'german government',
            'no deal',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/e6d9a44e-3f96-4d58-9618-bc022cea7300.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6164993700001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 85,
          created: '2020-06-17T16:26:50.725640+00:00',
          modified: '2020-06-17T17:40:08.941143+00:00',
          activatedAt: '2020-06-17T16:28:44.137456+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRKSIZ',
        },
        {
          id: '3624',
          title: 'Get ready for no-deal Brexit, Germany warns EU',
          description: "Berlin is warning other EU members to prepare for a no-deal Brexit, believing positions are far apart and time too short for an agreement. That's according to an internal government document seen by Reuters. Lucy Fielder reports.",
          summary: "Berlin is warning other EU members to prepare for a no-deal Brexit, believing positions are far apart and time too short for an agreement. That's according to an internal government document seen by Reuters. Lucy Fielder reports.",
          tags: [
            'boris johnson',
            'brexit',
            'european union',
            'german government',
            'no deal',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/b6109155-4778-4483-bd2a-7f2cd4c195de.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6164993684001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '11',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'Business',
          ],
          duration: 85,
          created: '2020-06-17T16:26:02.258111+00:00',
          modified: '2020-06-17T17:40:26.539088+00:00',
          activatedAt: '2020-06-17T16:28:06.550975+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRKSIZ',
        },
        {
          id: '3633',
          title: 'Black EU lawmaker reports Belgian police violence',
          description: 'Pierrette Herzberger-Fofana, a German Green party deputy who was born in Mali, told the European Parliament on Wednesday that she was a victim of "extremely traumatic" police violence outside a Brussels railway station. Olivia Chan reports.',
          summary: 'Pierrette Herzberger-Fofana, a German Green party deputy who was born in Mali, told the European Parliament on Wednesday that she was a victim of "extremely traumatic" police violence outside a Brussels railway station. Olivia Chan reports.',
          tags: [
            'belgium',
            'brussels',
            'european union',
            'german green party',
            'pierrette herzberger fofana',
            'police brutality',
          ],
          thumbnail: {
            url: 'https://oovvuu-thumbnails-prod.imgix.net/6/06b9e1c4-3335-4ae2-8fd2-0ba5f8994c6c.jpeg?h=281&w=500',
          },
          preview: {
            brightcoveVideoId: '6165013148001',
            brightcovePlayerId: '6aA69KYBi',
            brightcoveAccountId: '6146357338001',
          },
          collection: {
            id: '7',
            provider: {
              id: '6',
              name: 'Reuters',
              legalName: 'Reuters',
              logo: {
                url: 'https://oovvuu-logos-prod.imgix.net/6/80858aae-74ac-4f0a-8bb7-cf729c15b004.png?h=100&w=100',
              },
            },
          },
          genres: [
            'News',
          ],
          duration: 94,
          created: '2020-06-17T17:31:51.989249+00:00',
          modified: '2020-06-17T17:33:05.413136+00:00',
          activatedAt: '2020-06-17T17:33:05.413491+00:00',
          providerAssetId: 'tag:reuters.com,2020:newsml_OVCIRL3L7',
        },
      ],
      cursor: '{"v":1,"last":{"published_at":"2020-06-17T17:26:07Z","id":3633}}',
      hasMorePages: true,
    },
  },
};

export default latestVideosFixture;
