/* eslint-disable no-useless-escape */

const recommendedVideos = {
  hero: [
    {
      id: '13379',
      title: "The deadly impact of Covid-19 on Europe's care homes",
      description: "The coronavirus has swept through Europe's care homes killing thousands of residents. According to one recent study, on average the number of deaths account for half of the total victims. Speaking to families, care workers and associations, in this episode of Unreported Europe Euronews' Val\u00e9rie Gauriat investigates some of the best and worst practice. \r\n\r\n\"Over the past four days, every shift that I've been on, we've lost somebody, unfortunately.\" \r\n\r\nAnne Clark, carer. \r\n\r\nItaly's silent massacre \r\n\r\nPietro La Grassa works in the pharmacy of the Pio Albergo Trivulzio care home, one of the biggest in Europe. Located in the northern Italian city of Milan, like the Lombardy capital, the home was hit hard by the virus. Since the start of the country's health emergency more than 200 of its one thousand residents there have died.\u00a0A criminal investigation is underway. \r\n\r\nA trade union activist, Pietro believes many lives could have been saved if safety measures had been put in place weeks earlier. \r\n\r\n\r\n\u201cAt the beginning of March, some employees took the initiative to put on masks. They were reprimanded and forced to remove them, on the pretext they were frightening the patients,\" explains Pietro. He adds: \"The region needed to free up hospital beds, in order to prepare for what might happen with Covid, so it assigned patients to care homes. Unfortunately, there were no checks in these nursing homes!\" \r\n\r\nMore than a quarter of the home\u2019s 1000 strong work force, contracted the virus. Understaffed, the teams say they are exhausted and disillusioned. \r\n\r\n\"For those of us who are still working among those people, no tests whatsoever were done. And they continue to move us from one unit to another as if nothing has happened,\" says nurse Nadia Mordini. \r\n\r\n\"I had to put them in bags\" \r\n\r\nItaly is not alone. Many care workers throughout Europe have raised the alarm claiming the alleged wrongdoings in the nursing and care home sector are widespread. \r\n\r\nFor one Spanish care assistant we spoke to, the situation has become all too much. \r\n\r\n\"The dead... I had to put them in bags. I had to stretch them out because they died shrivelled up like this, I witnessed this. I had to close their eyes. I had to take them down to the morgue. And when the morgue was full, I took them to the underground car park,\" explains David P\u00e9rez Rivera. \r\n\r\nLike many, he also believes the deaths were avoidable. \r\n\r\n\"If an isolation unit had been opened at the start, where anyone who showed symptoms could have been transferred, and the other residents had been left in their rooms, and if all the carers had had the protective equipment, which were not delivered to them for 2 weeks, I can assure you that the spread of the virus in the home would not have occurred!\" \r\n\r\nAs in the case of Italy, Spain has also suffered greatly at the hands of the virus. That has inevitably led to questions over the authorities handling of the pandemic. Almudena Ariza's parents lived together in a retirement home. The couple died just days apart. Their children blame a lack of medical care for the deaths, saying their parents died under sedation, after their condition suddenly got worse. \r\n\r\n\"It's very hard, very difficult to imagine them like that, alone, or maybe together? Maybe blaming each other? says Almudena. \"How can I know?... I don't know. Neither my father nor my mother deserved to die this way. They were not allowed a place in a hospital, or a ventilator because they were 86 years old. For us, it just feels like they were completely abandoned. Our elderly are literally being abandoned.\" \r\n\r\n\"Billions in profit\" \r\n\r\nEurope\u2019s care home sector is concentrated in the hands of a few large private groups, often run by pension and investment funds. Eileen Chubb is the founder and Director of Compassion in Care, an organisation which seeks to improve conditions in the UK's care homes. Claiming the lucrative industry puts profits before safety, the former care worker turned whistleblower has long campaigned to highlight wrongdoings in the industry. Since the start of the Covid-19 outbreak, her helpline has received dozens of complaints from care home workers, whom she says feel they've been let down by their companies.   \r\n\r\n\"There's too many care companies that are quite willing to fill beds and they don't mind at what cost. And because care home staff are running on a wing and a prayer with staffing ratios, it doesn't take much to tip this over the edge, she insists, adding: \"These companies have made billions in profit, and then we've got a situation where they're saying they couldn't have foreseen this crisis and bought protective equipment for their staff. It is outrageous!\" \r\n\r\n\" Seventy-five percent of residents, and 51 percent of staff, were Covid positive\" \r\n\r\nThe lack of resources in many nursing homes in Europe has led, in some countries to the army being drafted in. At La Providence Saint Christophe care home in Belgium, the army had to be deployed after 17 out of 128 residents died during the first few weeks of the crisis. \r\n\r\n\u201cAt the start we didn\u2019t have the necessary protection. We tested everyone in the home on April 7 and it turned out that seventy-five percent of residents, and 51 percent of staff, were Covid positive. So we called in the military, because we didn't have enough staff left to take care of the residents,\" the home's Director Patrick Smousse said. \r\n\r\nHope in the face of despair \r\n\r\nDespite the wave of deaths, in a rare number of cases, some retirement homes have managed to stem the deadly tide. The Vilanova Care Home near the city of Lyon in south east France is one example. \r\n\r\n\"For several weeks, the director of this care home and a large part of the employees decided to totally isolate themselves, day and night, with the residents. The result, no one has been contaminated so far. In order not to jeopardise that, we film everything through windows.\" explains Val\u00e9rie Gauriat, Euronews International Reporter \r\n\r\nOn March 18, more than half of the staff in Vilanova, moved into the home bringing their suitcases and sleeping bags. Rallying around their director, they were determined to save the 106 residents. \r\n\r\n\"Our residents are not isolated to their rooms,\" says director Val\u00e9rie Martin. \"They are still able to have social contact with the other residents, as well as with us, as we see them all the time. They don't have the feeling of being abandoned or loneliness.\" \r\n\r\n\u201cEveryone is really lovely. They're a bit like family for me. I see the workers going back and forth, they come to say hello, then they go to do whatever they have to. It makes me really happy!\" one resident tells us. \r\n\r\nDespite the personal cost, the care staff agree that the huge effort has been worth it.   \r\n\r\n\"I have a 10-month-old son. So of course, he is at home and obviously he is changing, and I'm missing a lot of that. But for me it made sense to stay isolated here. To protect the residents, and to protect my family as well,\" one employee says. \r\n\r\nThe home\u2019s director Val\u00e9rie Martin believes lessons must be learned from a health crisis that has had a devastating impact on the care sector. \r\n\r\n\"It's taken a global catastrophe for people to realise what's really going on in nursing homes. And that is a lack of means, a lack of funds, a lack of staff, and a lack of recognition of our trade. And really now, money must be made available, and directed towards the old. The elderly are not a burden, they are our memory. So we have to love them, and be there for them. And above all, we need to make sure that they have a tender and pleasant life until the end,\" she says. \r\n\r\nAfter a total of 7 weeks of isolation, all the staff were tested for coronavirus: nobody was positive.",
      tags: ['coronavirus', 'covid 19', 'elderly people'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/db8c66a5-8d92-4fb6-9c11-e5ff15e2dcd7.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155337349001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 480,
      created: '2020-05-08T18:19:05.121214+00:00',
      modified: '2020-05-14T08:59:19.538137+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/08\/the-deadly-impact-of-covid-19-on-europe-s-care-home',
    },
  ],
  heroSecondary: [
    {
      id: '13306',
      title: 'How are people traveling to museums & art galleries from home',
      description: 'Virtual reality websites are becoming a ticket to cultural experiences for many who are currently self-isolating. \r\n\r\nPlatforms such as Google Arts and Culture, are permitting homebodies to electronically travel to around 2,000 cultural institutions in about 80 countries. \r\n\r\nThese include Spain\u2019s, currently closed, Guggenheim Museum. Online visitors can enter the monument of modernism free of charge and look upon famous works including Jeff Koon\u2019s multicoloured, stainless-steel, bouquet called, \u2018Tulips\u2019. \r\n\r\nAs for cultural sites in the Middle East and North Africa, the ancient Egyptian pyramids and Lebanon\u2019s Jeita Grotto - home to some of the world\u2019s largest stalactites - are proving popular digital destinations, according to the technology giant. \r\n\r\n\u201cMore people have been visiting the Google Arts and Culture website,\u201d says Luisella Mazza, the operations director of the Google Cultural Institute. \r\n\r\n\u201cAnd we are happy to see that more and more people find the diverse content that we make available through the arts and culture website, and through our free hub, worthwhile in these challenging times.\u201d \r\n\r\nDownloading culture \r\n\r\nTo keep things interactive, Google is using modern technology to create and upload digital replicas of famous artworks for users, on their application. \r\n\r\nThrough augmented reality, art fans can transport famous works, such as Vincent Van Gogh\u2019s \u2018The Starry Night\u2019, from the walls of the Museum of Modern Art in New York into their own living rooms. \r\n\r\nPeople can also use the \u2018Art Selfie\u2019 function to find their portrait look alike, by having their face scanned and compared to thousands of artworks displayed in museums across the globe. \r\n\r\nEntering the art matrix \r\n\r\nOther art institutions, and art forms, around the world are making use of online offerings. \r\n\r\nIn the UAE, for example, New York University Abu Dhabi staged a virtual poetry event called \u2018Rooftop Rhythms\u2019, which saw word spinners stream their lyrical art in an open-mic night. \r\n\r\nIn Dubai, the gallery-packed cultural district of Alserkal Avenue, which in its peak season of March, saw around 40,000 visitors last year, went into lockdown in 2020. \r\n\r\nBefore it did so, and in just a few days, the community digitized more than a thousand artworks to virtual galleries. \r\n\r\nHelping to make this a virtual reality was Tanzanian photographer Mohamed Somji, who has been a member of the Alserkal Avenue community since 2011. \r\n\r\nHe says that online galleries are creating unique, educational, experiences for art lovers. \r\n\r\n\u201cI think the added advantage to having a multimedia experience, is the ability to add on tags to these artworks - where you can get additional information,\u201d says Somji, who is a gallery owner and director of Gulf Photo Plus. \r\n\r\nArtful interfacing \r\n\r\nFor those who step inside Alserkal Avenue\u2019s 360-degree galleries, they can hear directly from the artists themselves, measure artworks for size and even purchase the pieces they want to display at home. \r\n\r\n\u201cIt\u2019s never going to replicate the experience of being there physically. Where you can actually see and experience for yourself, with your own eyes, the artwork\u201d says Somji. \u201c[Yet] it comes pretty close.\u201d \r\n\r\nNearly eight thousand virtual visitors entered their Alserkal Avenue\u2019s portal, since its digital premiere in March. \r\n\r\nAlthough relatively few purchases have been made since then, familiarity with digital art spaces is growing say some gallerists, perhaps implying that sofa surfing for art could become an avant-garde movement. \r\n\r\nSEEN ON SOCIAL MEDIA: REFLECTIONS \r\n\r\nUAE resident Loris from Lebanon worked on an art collection titled,  Min Hayati , or  From My Life . \r\n\r\nWith contributions from Nancy Sarkis, Ana De Oliva and Nicolas Tabbal.',
      tags: ['coronavirus', 'covid 19', 'culture', 'museum'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/56baeb39-f104-47c0-854d-1bc85cec0000.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155211502001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 209,
      created: '2020-05-08T09:36:01.921209+00:00',
      modified: '2020-05-13T12:14:14.663206+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/08\/how-are-people-traveling-to-museums-art-galleries-from-home',
    },
    {
      id: '13634',
      title: 'Confusion persists as England goes its own way in relaxing lockdown rules',
      description: "The loosening of lockdown restrictions specific to England come into play from today \u2013 causing major disparities with the rest of the UK.   \r\n\r\nThe government is encouraging people in England who cannot work from home to return to their occupations - but to avoid public transport. Facemasks in public places have also been recommended. \r\n\r\nThe government has faced some criticism that it is people in the lower-paid occupations who are being asked to face the greatest risk. The opposition Labour Party has said that the new guidelines are confusing. Police leaders have commented that advice for people to avoid public transport is \u201cunenforceable\u201d. \r\n\r\nThe advice to stay at home remains in place in the rest of the UK \u2013 Scotland, Wales and Northern Ireland. \r\n\r\nScotland's First Minister  Nicola Sturgeon  had said that the coronavirus is \"in retreat\" - but that the \"risk was still too great\" to consider easing the lockdown yet. She said that, despite the recent fall in the death toll and intensive care admissions, the progress that Scotland had made was as yet tentative and a premature loosening of restrictions could allow the situation to re-ignite. \r\n\r\nThe UK's central government has also announced a UK-wide extension of support for workers in furlough because of the pandemic. UK Chancellor Of The Exchequer  Rishi Sunak  said 7.5 million jobs had already been supported by the scheme, in which employees can receive up to 80% of their pay to a maximum of \u00a32,500 a month. The Treasury has said that nearly one million companies have sought government help to retain jobs, claiming more than \u00a310 billion.   \r\n\r\nSunak told British MPs there would be \"no change\" until the end of July but \"more flexibility\" from August onwards, including the possibility of bringing back part-time workers. \r\n\r\nBusinesses would also be asked to share the cost of salary support to maintain current levels of assistance. \r\n\r\nSunak's statement came after speculation that the scheme would be gradually reduced. \r\n\r\nThe London-based Institute for Fiscal Studies think tank said the extension of the scheme in its full form for the whole of July would cost another \u00a310 billion, taking the total cost to about \u00a360 billion since it was launched in March.",
      tags: ['coronavirus', 'england', 'lockdown', 'nicola sturgeon', 'united kingdom'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/ae05a257-b982-4840-ab9b-ef0693bc6884.jpg?h=281&w=500' },
      preview: null,
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 0,
      created: '2020-05-13T11:03:43.281883+00:00',
      modified: '2020-05-13T11:03:59.792929+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/13\/confusion-persists-as-england-goes-its-own-way-in-relaxing-lockdown-rules',
    },
    {
      id: '13632',
      title: 'Coronavirus live: England eases lockdown despite high death toll',
      description: "Here are the latest updates: \r\n\r\nThe easing of lockdown restrictions come into force in England from Wednesday (see blog below) \r\nThe changes have exposed differences of approach with the UK's other home nations \r\nUK death toll from COVID-19 passes 38,000 says Office for National Statistics \r\nItaly reports 1,402 new cases in large daily rise, mostly in Lombardy \r\n\r\nCOVID-19 outbreaks in German slaughterhouses expose grim working conditions in meat industry \r\nWill plastic pollution get worse after the COVID-19 pandemic? \r\nAnalysis: Africa's unexpected COVID-19 figures \r\nTable for one? Restaurant serving one guest in a field opens in Sweden",
      tags: ['coronavirus', 'covid 19', 'europe'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/a87bf39f-ee38-4e12-972a-5d41055ba226.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156269666001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 129,
      created: '2020-05-13T07:37:12.597707+00:00',
      modified: '2020-05-13T07:38:40.715609+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/13\/coronavirus-live-england-eases-lockdown-despite-high-death-toll',
    },
    {
      id: '13298',
      title: 'Coronavirus latest: Italy second European country to reach 30k COVID-19 deaths',
      description: "Key developments \r\n\r\nItaly on Friday became the second European country to officially record more than 30,000 COVID-19 deaths \r\n\r\nUS unemployment reached its highest level since records began in 1948 with 20.5 million jobs lost in April, official figures show \r\n\r\nWHO 'deeply troubled' by a spike in domestic violence in locked down Europe \r\n\r\nBanksy pays tribute to 'superhero' nurses in new piece donated to hospital \r\n\r\nBoris Johnson is to unveil the UK's lockdown exit roadmap on Sunday \r\n\r\n** Paris and three northeastern regions will have stricter rules than the rest of France on May 11 when the first restrictions are lifted, ministers have announced \r\n\r\n**WHO warned that between 83,000 and 190,000 could die from COVID-19 across the African continent this year if containment measures fail. \r\n\r\nBelarus, Kazakhstan, Russia and Ukraine seeing an increase in cases, says WHO \r\n\r\nNine die in Hungary after being ejected from hospital to free space for COVID-19 \r\n\r\nLatest updates",
      tags: ['coronavirus', 'covid 19', 'europe'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/598e9112-9b0a-4f0e-bb69-4fc7ce89f732.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155181751001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 134,
      created: '2020-05-08T07:41:04.193408+00:00',
      modified: '2020-05-13T07:27:14.060794+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/08\/coronavirus-live-eu-promises-aid-to-pakistan-as-south-korea-records-new-cases',
    },
    {
      id: '13631',
      title: 'Mental health in the time of COVID-19: are we doing enough?',
      description: "Even as some parts of Europe are beginning to wind down containment measures, the effects of quarantine and self-isolation on mental health are continuing to draw concern. \r\n\r\nIn addition to the elevated levels of stress and worry, health authorities are raising awareness of the added impact that the COVID-19 outbreak could have on citizens' psychology. \r\n\r\nThe World Health Organization says \"levels of loneliness, depression, harmful alcohol and drug use, and self-harm or suicidal behaviour\" are expected to have risen due to a disruption in normal life activity. \r\n\r\nOlder adults, care providers and people with underlying health conditions are groups of particular concern, as well as frontline health workers. \r\n\r\nIn areas heavily affected by coronavirus, citizens have limited access to services; this can impact mental wellbeing. \r\n\r\n\"People are having to do a lot of things that are out of the ordinary for them,\"  Dr. Christopher Hand,  a lecturer in psychology at Glasgow Caledonian University,  told Euronews . \r\n\r\n\"It is a very difficult time, particularly for people that have young families, or vulnerable adults to care for and the uncertainty around the situation is certainly not helping\". \r\n\r\nSo what are the protocols for tackling mental health? \r\n\r\nThe WHO Regional Office for Europe  says that mental disorders are \"one of the top public health challenges\" in the region, affecting around 25% of the population every year. \r\n\r\nDuring the COVID-19 pandemic, the WHO says that they have worked with national authorities to develop \" a set of new materials \" on supporting mental health. \r\n\r\n\"Psychosocial support services should be in place, and child protection services need to adapt to ensure that the care is still available for the children of families who need it,\" says the WHO. \r\n\r\nThrough the European Action Plan, the WHO had recommended that governments develop  \"community-based\" mental health services  by 2020. \r\n\r\nThis strategy would seek to avoid over-reliance on large public facilities and provide balance and investment to specific professionals in the field. \r\n\r\nActions that European countries have been encouraged to support include: \r\n\r\nEstablishing primary care as a first point of access to treat common mental disorders \r\nOffering special outreach programmes in areas with a high prevalence of risk, such as poor minority groups or homeless people; \r\nDeveloping psychiatric units, which are therapeutic, to offer effective care \r\nEnsuring forensic mental health services are managed by specially trained services \r\nRemoving obstacles to accessing care for mental health e.g. transport, finances \r\n\r\nBack in March, the WHO Department of Mental Health and Substance Use also issued a  series of recommendations for citizens  to cope with mental health during the pandemic. \r\n\r\nThe advice included minimising exposure to news about COVID-19 and offering support to those in need in the local community. \r\n\r\nBut the World Health Organization does say that some authorities in Europe were struggling to implement the strategies listed in the European Action Plan. \r\n\r\nMeanwhile, there are additional concerns that the drain of healthcare resources due to COVID-19 may be restricting necessary investment to mental health facilities. \r\n\r\nJennifer Oroilidis, of Mental Health Europe says that some public authorities had closed healthcare services during the pandemic \" due to a lack of focus on social care \". \r\n\r\n\"Public authorities must take urgent measures to protect their well-being and to ensure access to vital services during this time of crisis\". \r\n\r\n\"Without immediate intervention, the consequences of the current inaction by governments will lead to a long-term negative impact on economies and communities, while leaving thousands of people experiencing mental health distress without the care they so urgently need. \r\n\r\nEnding lockdown could be another factor \r\n\r\nEven the prospect of the lockdown ending may not bring relief for many; mental health experts are noticing an emerging phenomenon concerned with anxiety about life after lockdown. \r\n\r\nDave Smithson, Operations Director at  Anxiety UK , says the prospect of a second dramatic change to the \"new normal\" is difficult for many people whose mental health has already suffered:  \r\n\r\n\"We had a survey of our members at the weekend ahead of the Prime Minister\u2019s announcement and 67% of them reported an increase in their anxiety levels at the prospect of the easing of the restrictions. \r\n\r\n\"Of those, the biggest fear was of contracting the virus: 57% cited that as their biggest concern. \r\n\r\n\"We need to give people time and space to get used to returning to normal after being inside after such a long time. \r\n\r\n\"It\u2019s obviously going to feel really strange and be challenging for people to return to their pre-pandemic routine. This is to be expected, especially for those with pre-existing anxiety disorders.\"  \r\n\r\nSmithson concludes that proper support for people disturbed by this next approaching upheaval is essential:  \r\n\r\n\"As we release these restrictions and we let people return to normal, we must make additional support available for that group of people.\"",
      tags: ['coronavirus', 'covid 19', 'mental health', 'pandemic', 'psychology', 'world health organization'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/8c25a687-e9f6-4f0e-8295-05cc22bcff10.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156174059001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 154,
      created: '2020-05-12T21:21:23.649330+00:00',
      modified: '2020-05-12T21:22:52.673475+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/mental-health-in-the-time-of-covid-19-are-we-doing-enough',
    },
    {
      id: '13627',
      title: 'COVID-19 outbreaks in German slaughterhouses expose grim working conditions in meat industry',
      description: "Working conditions for migrants in German slaughterhouses are under the spotlight after more than 200 workers tested positive for COVID-19 at a factory in Coesfeld, in the west of the country. \r\n\r\nCoronavirus outbreaks have also been identified in at least two other meat processing plants in Germany. The majority of those infected were from Romania and Bulgaria. \r\n\r\nOfficials say the virus  most likely spread through shared staff housing , and the outbreaks are drawing attention to the industry\u2019s difficult working conditions. \r\n\r\n\"Workers in the German meat industry work very often through subcontractors, not for the slaughterhouses themselves, and the working conditions at these subcontractors are often very, very bad,\" said Szabolcs Sepsi, a counsellor at  DGB Fair Mobility , which defends migrant workers\u2019 rights in Germany. \r\n\r\nThese workers contend with \"extremely long working hours\" insecure jobs and often squalid housing, Sepsi told Euronews in a live interview, adding that they typically share their bedroom with two or three other people and are shuttled to work together. \r\n\r\n\"Their living conditions simply do not allow social distancing measures,\" he said. \r\n\r\n'Modern slavery' \r\n\r\nGerman broadcaster Deutsche Welle spoke to meat workers crammed in decrepit homes, writing that the outbreaks exposed \" modern slavery \" in the industry.   \r\n\r\nThere have been outbreaks of COVID-19 at slaughterhouses  in a number of countries  in recent weeks, mostly in the United States but also in the UK, Ireland, Australia and Spain. \r\n\r\nThe trend is starting to expose an uncomfortable reality: much of the cheap meat on Western supermarket shelves is slaughtered by migrant workers who earn low wages, often live together in dorms and operate in crowded working conditions even in the midst of a pandemic. \r\n\r\n\"It\u2019s mostly the workers in the meat industry and other food industries who are actually paying the price for this cheap meat and for the cheap food,\" Sepsi said. \r\n\r\nAfter years of debate and controversy, Germany introduced a minimum wage in 2015. It stands at  around \u20ac1,500 per month  gross for full-time workers. \r\n\r\nBut Sepsi says the various laws introduced over the past decade to improve the lives of migrant workers in the German meatpacking industry only address the symptoms and not the root of the problem: the fact that most slaughterhouse workers are hired by subcontractors that try to undercut each other. \r\n\r\n\"We believe the slaughtering companies have to hire people directly and give them direct jobs,\" he said, adding this would help workers afford their own apartments instead of having to live together in dormitories during a pandemic. \r\n\r\nYou can watch the interview in the video player above.",
      tags: ['coronavirus', 'health', 'meat industry', 'migrants', 'slaughter', 'workers'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/997af024-a1cb-4e06-90dd-101c953c2123.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156129652001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 147,
      created: '2020-05-12T17:45:13.239416+00:00',
      modified: '2020-05-12T17:46:59.819852+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/covid-19-outbreaks-in-german-slaughterhouses-expose-grim-working-conditions-in-meat-indust',
    },
    {
      id: '13626',
      title: 'Will we ever shake hands again?',
      description: "The Covid-19 pandemic has brought a temporary end to one of the world's oldest greeting signals: The Handshake. However, given their potential to help spread disease, will they ever become the norm again?",
      tags: ['boris', 'coronavirus', 'covid 19', 'handshake', 'health', 'macron', 'pandemic', 'trump'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/97738f0f-fe8e-4ecb-ab0d-4aa846825cfe.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156122666001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '9',
        provider: {
          id: '1', name: 'Oovvuu', legalName: 'Oovvuu Pty Ltd', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/1\/19451105-545d-441f-a7d3-e6f083c90c28.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 94,
      created: '2020-05-12T17:20:15.378147+00:00',
      modified: '2020-05-12T17:21:45.852625+00:00',
      activeSince: null,
      providerAssetId: '78360',
    },
    {
      id: '13624',
      title: 'Coronavirus: Belgians allowed to socialise again - but only with same four people',
      description: "People in Belgium have been gathering in small groups again after the government eased the country's COVID-19 lockdown.  \r\n\r\nUnder the new measures, people are allowed to meet up with a maximum of four others that are not from their household.  \r\n\r\nBut the four they meet up with must remain the same until further notice - meaning people have had to make tough decisions about who they choose. \r\n\r\nEuronews went to Carla Mauricio's flat in Brussels as she was preparing to have friends over for the first time in more than eight weeks. \r\n\r\nOriginally from Barcelona, Carla works for an EU science organisation. \r\n\r\n\u201cThis marks a new phase of the deconfinement and I was very much looking forward to it of course, and even more so (towards) the new phases of deconfinement,\" she said.  \r\n\r\nShe and her boyfriend provide hand gel on entry for the two friends they have invited over. The four friends sit at the furthest four corners of the table, respecting the 1.5-metre social distancing rules. \r\n\r\nAnnouncing the relaxing of measures on May 6, Belgian Prime Minister  Sophie Wilm\u00e8s  said she understood the pressure that confinement had put on people. \r\n\r\nThe prime minister's orders are that \"every family may receive a maximum of four people - always the same people - at home. To limit the number of contacts and to prevent the spread of the virus, visitors can only meet with one family.\" \r\n\r\nThe government is warning people to proceed with caution, saying a new spike in infections could mean that they have to reintroduce stricter rules. \r\n\r\nXavier Noel, Professor of Psychology at Brussels'  ULB University , warns that it will be very difficult to reverse these measures: \r\n\r\n\u201cI would be worried about how people will consent to isolation once again and I think our government agrees with that and is aware of that.\u201d \r\n\r\nNot everyone in Belgium has been so eager to immediately get together with their friends.   \r\n\r\nBob Eck, who lives in the Flemish city of Bruges, says his personal experience with COVID-19 means he won\u2019t come out of lockdown until the pandemic is actually over. \r\n\r\n\u201cWe lost one of our friends,\" he said. \"He went from healthy to dead in six days and we saw firsthand how quickly things can occur. And if that\u2019s not enough evidence to just chill and wait, I don't know what is.\u201d \r\n\r\nBelgians are beginning to reunite with one another, but the coronavirus pandemic is far from over and public health experts are warning that the loosening of measures across Europe is likely to lead to a second wave of infections.",
      tags: ['belgium', 'brussels', 'coronavirus', 'end of lockdown'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/0ae2a94d-f9e8-46b6-8cc9-0e15e4211697.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156100257001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 125,
      created: '2020-05-12T15:52:14.256757+00:00',
      modified: '2020-05-12T15:53:25.921968+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/coronavirus-belgians-allowed-to-socialise-again-but-only-with-same-four-people',
    },
    {
      id: '13623',
      title: 'Chain reaction: commuters and cities embrace cycling in COVID-19 era',
      description: "It\u2019s a great way to get some exercise on the way to work while limiting air pollution in our cities. \r\n\r\nNow millions of commuters across Europe are turning to cycling to avoid crowded public transport throughout the coronavirus pandemic. \r\n\r\nAs countries start to ease lockdown restrictions to get their economies up and running again, authorities are rushing to ensure that it's not just the wheels of industry that have started turning again. New cycle paths are being created to encourage people to hop onto their bikes rather than into their cars.   \r\n\r\nLeaders and urban planners say it\u2019s a unique opportunity to advance green policy goals while encouraging social distancing. \r\n\r\n\"What we\u2019re seeing across Europe is a brilliant move in cities like Oslo, Helsinki, Copenhagen, Paris, Milan, Vienna \u2013 the list is extremely long now \u2013 that will remove the old, obsolete care infrastructure and actually make infrastructure for all of us,\" Morten Kabell, CEO of the  European Cyclists' Federation , told Euronews in a live interview. \r\n\r\nCapitals including London, Paris, Brussels and Rome are scrambling to set up hundreds of kilometres of new cycle paths. Authorities in France are subsidising bike repairs and electric bike purchases. \r\n\r\nParis has also banned cars from the famous shopping street of Rue de Rivoli, near the Louvre Museum, to favour bikes instead. \r\n\r\nIn Barcelona, existing bike lanes are being widened so that cyclists can keep their distance from others, and new ones are being created. \r\n\r\nBefore the pandemic accelerated the creation of cycle paths across Rome, existing lanes often weren't connected \u2013 forcing cyclists to brave busy and dangerous roads. The capital\u2019s transport councillor has now promised the new lanes would remain in place even after the crisis. \r\n\r\n\"We are very happy. We have been asking for them for years,\" said Enzina Fasano, president of the 'Save the Cyclists' association. \"We were simply asking for a sign of civic sense and dignity for cyclists.\" \r\n\r\nThat all sounds great. But is it safe? \r\n\r\nWeeks-long transport strikes in France this winter led to an increase in cycling, alongside an  increase in cycling accidents . With more people on the road, how can riders stay out of harm\u2019s way? \r\n\r\nFirst off, remember to wear a helmet, as well as high-visibility gear if you're cycling at night or at dawn. And if you like to listen to podcasts in one ear, make sure you always stay aware of what's going on around you.   \r\n\r\nThe rest, says Kabell of the European Cyclists' Federation (ECF), lies in the hands of urban planners.   \r\n\r\n\"We need to have safe, permanent infrastructure in all our cities. Most of these accidents happen because the infrastructure is not ready for the huge amount of bicycles that we\u2019ll see in the future,\" he said. \r\n\r\n\"But with separate, safe bicycle lanes \u2013 as you see them in Copenhagen or in the Netherlands \u2013 then we will avoid a lot of these accidents. If you look at the numbers there, cycling is the safest way to get around our towns. And so it could actually be for all our cities.\" \r\n\r\nThe  ECF recommends  setting up dedicated bike paths, bringing down speed limits, introducing congestion charges for motor vehicles and subsidising bike purchases, among other suggestions.   \r\n\r\nWhat about shared bikes? \r\n\r\nKabell says regular hand washing and use of hand sanitizer, as well as common sense, should be enough to make bike-sharing schemes safe to the public. \r\n\r\nMadrid's municipal bicycle sharing scheme BiciMAD reopened in late April after being closed for over a month as part of measures to help stop the spread of the new coronavirus. \r\n\r\nCyclists are now allowed to ride the bikes, which are disinfected several times a day, as long as they wear gloves. \r\n\r\nYou can watch the interview with Morten Kabell in the video player above.",
      tags: ['coronavirus', 'covid 19', 'cycling', 'green transportation', 'life after lockdown', 'urban planning'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/7e4f9613-e24c-4680-b36c-e20240252cfc.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156093660001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 136,
      created: '2020-05-12T15:31:12.828504+00:00',
      modified: '2020-05-12T15:32:25.994682+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/chain-reaction-commuters-and-cities-embrace-cycling-in-covid-19-era',
    },
    {
      id: '13622',
      title: 'Increased transmission of coronavirus in Germany, public health officials say',
      description: "The coronavirus reproduction number has been slightly above one since Saturday, said Professor Lars Schaade at Germany's public health body, the Robert Koch Institute (RKI). \r\n\r\nThe reproduction number (or R-value) describes how many people a person with coronavirus will infect on average.   \r\n\r\nWhen the R-value is above one, you risk an exponential increase in cases. \r\n\r\nAt a press conference, the German public health body RKI said that the number of cases in Germany is slowly decreasing, so individual outbreaks will have a greater influence on the R-number. \r\n\r\nThere are new clusters in Germany linked to slaughterhouses in particular. \r\n\r\nThe fact that the R-value has been above 1 for a short time was not too worrying, the RKI said.   \r\n\r\nThe number of new daily infections, the severity of illness and the number of tests carried out are all important as well.   \r\n\r\nIf R stays above one for a longer time period and reaches 1.1,  they would need to investigate further as it could indicate a new wave of infections.   \r\n\r\nThere are currently 170,508 confirmed cases in Germany, including 933 new cases. There have been 7,661 deaths in the country. The percentage of people who have died is currently at 4.4 per cent.   \r\n\r\nGermany has been largely praised for its response to the pandemic, with a much lower death toll than many other large European countries.   \r\n\r\nYet many countries in Europe are preparing for a second wave of coronavirus infections as lockdown restrictions are eased.   \r\n\r\nSouth Korea, another country that has been seen as handling the crisis well, has reported new clusters of coronavirus cases linked to nightclubs in Seoul, after largely containing their outbreak.",
      tags: ['coronavirus', 'covid 19', 'europe', 'germany'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/a0dbe456-332e-4c69-8356-9eac2ac2042b.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156057892001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 51,
      created: '2020-05-12T13:19:13.843565+00:00',
      modified: '2020-05-12T13:20:21.580334+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/increased-transmission-of-coronavirus-in-germany-public-health-officials-say',
    },
  ],
  heroEmptyReason: null,
  positionTwo: [
    {
      id: '13644',
      title: "Coronavirus live: 'This virus may never go away,' warns World Health Organization",
      description: "The latest updates (see live blog below for details): \r\n\r\nWorld Health Organization warns coronavirus may never be fully eradicated \r\n\r\nUN Secretary-General calls for action on mental health to tackle 'psychological suffering'  \r\n\r\nSummer holiday rescue package? EU sets out plan to save your vacation \r\nGermany, Austria and Switzerland plan to reopen borders from June 15 \r\n\r\nUK government pledges \u20ac680 million to fight virus in care homes \r\n\r\nBritain's iconic Old Vic theatre facing financial collapse due to pandemic \r\nEurope redeploys funding firepower to fight Covid-19 \r\n\r\nParis\u2019 mayor clashes with government over reopening of parks and gardens",
      tags: ['coronavirus', 'covid 19', 'europe'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/43835745-98bf-4d8a-9761-d1fd87d7805b.jpg?h=281&w=500' },
      preview: null,
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 0,
      created: '2020-05-14T07:38:20.562136+00:00',
      modified: '2020-05-14T07:38:39.610308+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/14\/coronavirus-live-un-chief-calls-for-action-on-mental-health-to-tackle-psychological-suffer',
    },
    {
      id: '13639',
      title: 'Coronavirus: EU governments urged to do more for cancelled flight refunds',
      description: "European governments need to do more to protect the rights of consumers struggling to get reimbursed for cancelled flights, one of the architects of the EU\u2019s legislation on passenger rights told Euronews. \r\n\r\nFormer MEP Mark Watts is the coordinator of UK Transport in Europe. He helped write an EU regulation that  requires airlines to offer refunds within seven days . \r\n\r\n\"Of course the airlines have a cash flow crisis, but it\u2019s probably nothing compared to the cash flow crisis being faced by many households, who may have hundreds of euros locked up in flight tickets that they cannot use this summer,\" Watts told Euronews in a live interview. \r\n\r\n\"They (consumers) need that money back, and I think there\u2019s a financial but also a moral obligation on the part of the airlines to pay this money back.\u201d \r\n\r\nThe European Commission is still hoping to salvage Europe's summer tourist season with  a plan to gradually open borders and lift travel restrictions  for holidaymakers. \r\n\r\nAs it unveiled its recommendations on Wednesday, it also called on companies to uphold travellers\u2019 rights to get refunds for cancelled trips and suggested ways to make vouchers \"a more attractive option for consumers\". \r\n\r\n\"The voluntary vouchers should be protected against insolvency of the issuer, with a minimum validity period of 12 months, and be refundable after at most one year, if not redeemed,\"  the Commission said in a statement . \r\n\r\n\u201cThey should also provide passengers sufficient flexibility, should allow the passengers to travel on the same route under the same service conditions or the travellers to book a package travel contract with the same type of services or of equivalent quality. They should also be transferable to another traveller.\u201d \r\n\r\n'Consumers are not banks' \r\n\r\nThe move comes after a coordinated attempt from a majority of EU countries  to suspend the right to a refund and impose vouchers  to give struggling airlines some breathing space. \r\n\r\n\"It is precisely in times of crisis such as these that travellers should be able to rely on strong consumer rights,\" said Monique Goyens, director-general of the  European consumer group BEUC . \r\n\r\n\"Trying to make consumers bail out transport and travel companies through cheap credit in the form of vouchers is unacceptable: consumers are not banks. We are glad the European Commission agrees and shows the way.\" \r\n\r\nThe European Commission also signalled that member states will now be free to introduce state guarantee schemes for airline vouchers without having to go through traditional state aid clearance procedures. \r\n\r\nWatts, the former MEP, welcomed the move, saying company coupons would be much more attractive \"if people knew they could take the voucher without the airline going bust whilst they\u2019re waiting for their rescheduled flight\". \r\n\r\nHe urged the European commission to get airlines, insurers, and member states around the table to address the issue as quickly as possible. \r\n\r\n\"Let\u2019s do that in days, not weeks or months,\" he said. \r\n\r\nWatch the interview with Mark Watts in the video player above.",
      tags: ['airlines', 'consumer protection', 'coronavirus', 'covid 19', 'eu commission', 'passengers rights'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/f29d4c79-1cfa-420a-96a2-6199fc418335.jpg?h=281&w=500' },
      preview: null,
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 0,
      created: '2020-05-13T16:51:15.604258+00:00',
      modified: '2020-05-13T16:51:35.153772+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/13\/coronavirus-eu-governments-urged-to-do-more-for-cancelled-flight-refunds',
    },
    {
      id: '13638',
      title: 'Coronavirus: Dress shops and florists left at the altar as COVID-19 hits weddings',
      description: "Whether they prefer an A-line, ball gown or mermaid silhouette, most brides this year will have to wait a little longer to wear their dream wedding dress. \r\n\r\nDue to coronavirus containment measures, gatherings of more than 10 people are still widely banned across Europe, making parties and celebrations very tricky or downright impossible to organise. Many soon-to-be brides and grooms have been forced to postpone their big day. \r\n\r\nIn Italy alone, 17,000 marriages were cancelled in March and April, and another 50,000 are expected to be scrapped in May and June. \r\n\r\nOwners of wedding dress shops are now also worried that people won\u2019t be able to afford their postponed wedding next year. \r\n\r\n\"I had many clients, I may have even sold more dresses this year than all the other years put together, but as you can see they are all waiting to be worn,\u201d says Manuela Tanno, owner and designer of Manuela Atelier in the Italian city of Campobasso. \r\n\r\nAccording to Assoeventi, which studies the events sector in Italy, the nation\u2019s wedding industry is down between 80 per cent and 100 per cent and is forecast to lose about \u20ac26 billion in revenue. \r\n\r\nThat includes small- and medium-sized businesses like florists and photographers and gift producers. \r\n\r\nVogue Spose, a wedding dress store also in Campobasso, is being hit hard by the wave of cancellations. \r\n\r\nWith an average price tag of \u20ac2,000-2,500, each one of its unsold dresses is taking a toll. \r\n\r\n\"In terms of quantities, living in a region like ours, we are talking about 90, 95, even 100 dresses a season, so it's a major loss,\u201d says owner Michela Fagnano. \r\n\r\nWeddings in Italy are traditionally large affairs and sometimes last for several days. \r\n\r\nAs Italy begins to ease its lockdown restrictions, couples can now get married but they cannot host big parties to celebrate. \r\n\r\nWatch Katy\u2019s report in the video player above.",
      tags: ['coronavirus', 'covid 19', 'economic crisis', 'italy', 'small and medium sized enterprises smes', 'wedding'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/34dfccd8-fe9c-472a-abea-3698a8219e51.jpg?h=281&w=500' },
      preview: null,
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 0,
      created: '2020-05-13T16:00:17.579749+00:00',
      modified: '2020-05-13T16:00:36.371243+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/13\/coronavirus-dress-shops-and-florists-left-at-the-altar-as-covid-19-hits-weddings',
    },
    {
      id: '13635',
      title: "Kate's lockdown wardrobe",
      description: "We take a look at some of the Duchess of Cambridge's lockdown wardrobe.",
      tags: ['coronavirus', 'covid 19', 'duchess of cambridge', 'health', 'kate', 'lockdown', 'looks', 'middleton', 'wardrobe'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/5a50938e-1750-4e2a-a465-b3f75b53ea0c.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156322119001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '9',
        provider: {
          id: '1', name: 'Oovvuu', legalName: 'Oovvuu Pty Ltd', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/1\/19451105-545d-441f-a7d3-e6f083c90c28.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 44,
      created: '2020-05-13T12:38:18.121347+00:00',
      modified: '2020-05-13T12:39:30.969034+00:00',
      activeSince: null,
      providerAssetId: '78393',
    },
  ],
  positionTwoSecondary: [
    {
      id: '13620',
      title: 'Life on the inside: Stretches to help your body and mind during lockdown',
      description: 'Even if you\u2019re diligent with working out at home, most of us are still moving our bodies less in lockdown.\n\nWhen your commute is walking from your bedroom to the kitchen and you\u2019re only allowed out of the house for an hour a day, it\u2019s easy for your muscles to feel tight and your general mood lethargic.\n\nIncorporating stretches into your daily routine can go a long way to helping your body and mind.',
      tags: ['coronavirus', 'covid 19', 'fitness', 'lifestyle', 'lockdown', 'lockdown fitness', 'yoga'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/1\/5ec6a2ca-49df-40b7-9f8e-44b3ce0486df.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156049694001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '9',
        provider: {
          id: '1', name: 'Oovvuu', legalName: 'Oovvuu Pty Ltd', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/1\/19451105-545d-441f-a7d3-e6f083c90c28.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 84,
      created: '2020-05-12T12:43:10.950198+00:00',
      modified: '2020-05-12T12:44:52.920288+00:00',
      activeSince: null,
      providerAssetId: '78325',
    },
    {
      id: '13618',
      title: "Putin criticised for ending 'non-work period' amid record Russian COVID-19 figures",
      description: "Russian President Vladimir Putin's decision to end what he describes as the \"non-working period\" is drawing sharp criticism from his political opponents.   \r\n\r\nPutin said on Monday that orders to remain at home would end this week for most of the country\u2019s workforce, despite a record increase in new coronavirus infections. \r\n\r\nWith more than 220,000 confirmed cases and consistently more than 10,000 new coronavirus cases per day, Russia now ranks fourth in the world behind the United States, Spain and the UK. \r\n\r\nMonday's figures saw Russian health officials put the total number of infections at 221,344, with around half of the total cases in the capital, Moscow. \r\n\r\nPutin\u2019s critics say the reopening is being driven by financial concerns and isn't supported by the scientific data. They're also accusing the Russian premier of trying to shift responsibility onto regional authorities. \r\n\r\nDimitry Gudkov, leader of the opposition Party of Changes said Putin\u2019s actions were motivated by trying to save money and shift blame. \r\n\r\n\u201cPutin does not want to give money, does not want to spend the money of the Reserve Fund. He's decided to put all the responsibility on (local) governors, so it will be they who will continue the bans and they will bear responsibility for the spread of the coronavirus. \r\n\r\n\"It\u2019s all as if Putin had nothing to do with it -- he withdrew this responsibility from himself.\" \r\n\r\nThe Kremlin introduced the measures in late March, saying Russians not working in essential jobs should remain at home but still receive their salaries as part of comprehensive measures to halt the spread of the virus. \r\n\r\nThe move brought further uncertainty to an economy already dealing with low oil prices and with business owners struggling to pay full salaries to employees while shutting their doors to customers. \r\n\r\nPresident Putin said that Russia's regions, which were given powers to introduce varying measures to deal with the pandemic, will be able to keep in place any restrictions they considered necessary to contain the virus.",
      tags: ['coronavirus', 'moscow', 'russia', 'vladimir putin'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/0c1d4a48-004e-4bdb-bd0f-b9d10bd644f4.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156029557001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 141,
      created: '2020-05-12T11:25:11.475222+00:00',
      modified: '2020-05-12T11:26:23.214518+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/putin-criticised-for-ending-non-work-period-amid-record-russian-covid-19-figures',
    },
    {
      id: '13617',
      title: 'Europe warned of second waves of COVID-19',
      description: "Countries are  starting to ease the lockdown measures  and there is fear in Europe of a new wave of infections towards the summer. \r\n\r\nExperts warn lower infection rates combined with higher temperatures could lead to complacency among people to respect social distancing and hygiene rules. \r\n\r\nBased on studies of previous pandemics, experts say a second wave is likely to occur this time as well. \r\n\r\nIt's reason enough for Brussels to remind governments of what is at stake. \r\n\r\nStefan de Keersmaecker, a spokesperson for the European Commission, says, \"member states should prepare for eventual second waves of infections by taking any opportunity to enhance the existing surveillance systems.\" \r\n\r\nBrussels says it remains committed to working with European Centre for Disease Prevention and Control to insure that there is inaugurated risk communication. \r\n\r\nDe Keersmaecker says, \"this is key to ensure that the citizens understand that new waves can occur, even if an initial wave is successfully managed.\" \r\n\r\nEU Member States are called upon to lift the restrictions gradually and carefully, taking into account the epidemiological data available. \r\n\r\nSome Members of the European Parliament say that the EU should be given more competence on healthcare in the future. \r\n\r\nJytte Guteland is a Swedish socialist MEP and says, \u201cI think the corona crisis showed cooperation between member states on health policy. I think we need a discussion on having more competence on the EU level to tackle pandemics in the future\u201d. \r\n\r\nIn Germany, the authorities set a limit of 50 new infections per week per 100,000 inhabitants. \r\n\r\nIf the number of infections increases, stricter measure are set to be reimposed. \r\n\r\nAccording to the Dr. Klaus Cichutek, president of thePaul-Eh rlich-Institut German research institute, every country should have enough intensive care units ready as well as places in hospitals for those people who suffer from COVID19. \r\n\r\n\"We have to win time for finding therapies we are doing a lot of scientific work on the side of bio-medicine to decrease the time for vaccine development which is, of course, the public health measure that would help us most in the long run\" says Dr. Klaus Cichutek. \r\n\r\nMost experts warn a second wave is not a question of if, but when. \r\n\r\nMany EU countries like Belgium and France are also relaxing lockdown measures after 2 months. \r\n\r\nThe COVID19 pandemic is still not over.",
      tags: ['coronavirus', 'covid 19', 'european union'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/48bf98e3-4a3e-4a3c-869f-afe3711c524f.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6156027891001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 121,
      created: '2020-05-12T11:05:15.457375+00:00',
      modified: '2020-05-12T11:06:41.546627+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/11\/europe-warned-of-second-waves-of-covid-19',
    },
    {
      id: '13615',
      title: 'Coronavirus live: Trump clashes with Asian American reporter as US deaths pass 80,000',
      description: "Tuesday's latest updates: \r\n\r\nDonald Trump clashes with Asian American reporter as US deaths pass 80,000 (see blog below) \r\n\r\nPutin declares end to Russia's partial economic shutdown despite mounting COVID-19 cases \r\n\r\n\r\nBoris Johnson grilled on 'vague' UK coronavirus lockdown advice \r\n\r\nUK prime minister says 'common sense' will help beat coronavirus \r\n\r\nEurope warned of second waves of COVID-19 \r\n\r\n\r\nAs shops reopen in Greece, owners fear second wave \u2013 and second lockdown \r\n\r\n\r\nFootball restarts in Europe as Faroe Islands kick off season \r\n\r\n\r\nLife after lockdown: Will our social habits be changed forever?",
      tags: ['coronavirus', 'covid 19', 'europe'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/5\/0f36c685-bcfc-402c-8953-594105990e08.jpg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155980883001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '6',
        provider: {
          id: '5', name: 'Euronews', legalName: 'Euronews', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/5\/5850b793-67b0-48c0-b346-13e1dd79a059.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 121,
      created: '2020-05-12T07:06:13.921300+00:00',
      modified: '2020-05-12T07:07:25.509896+00:00',
      activeSince: null,
      providerAssetId: 'https:\/\/www.euronews.com\/2020\/05\/12\/coronavirus-live-trump-clashes-with-asian-american-reporter-as-us-deaths-pass-80-000',
    },
    {
      id: '13613',
      title: "'World's tallest donation box' lights up after Covid-19 appeal",
      description: "The world's tallest building, the Burj Khalifa, was transformed into the world's tallest donation box in a spectacular light show to mark the United Arab Emirates  smashing its target of fundraising for 1.2 million meals or food parcels for individuals and families affected by the coronavirus outbreak in the country.",
      tags: ['burj khalifa', 'coronavirus', 'covid 19', 'uae'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/9\/f0a266f6-1ec9-4b38-9dc9-4ca31dcec4c8.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155950859001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '5',
        provider: {
          id: '9', name: 'Press Association', legalName: 'Press Association', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/9\/35fe0f0c-b518-4b63-92f7-e41ee2a545e0.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 30,
      created: '2020-05-12T03:11:11.123104+00:00',
      modified: '2020-05-12T03:12:21.605523+00:00',
      activeSince: null,
      providerAssetId: '78295',
    },
    {
      id: '13609',
      title: "'Ask China' - Trump abruptly ends briefing after heated exchange",
      description: "Monday's Rose Garden event on coronavirus testing came to an end after U.S. President Donald Trump was challenged by a reporter for CBS News.",
      tags: ['cbs', 'china', 'coronavirus', 'covid 19', 'donald trump', 'rose garden', 'testing', 'weijia jiang'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/4\/b5a49034-1a96-47c6-b013-72d4e86be200.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155911514001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '12',
        provider: {
          id: '4', name: 'Reuters', legalName: 'Reuters', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/4\/f7ec6d22-dfbf-4d8e-9ad6-7d798ec38ba7.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 72,
      created: '2020-05-11T23:17:32.745335+00:00',
      modified: '2020-05-11T23:18:59.228392+00:00',
      activeSince: null,
      providerAssetId: 'tag:reuters.com,2020:newsml_OVCDHSXCV',
    },
    {
      id: '13603',
      title: 'Nasdaq climbs for 6th day in a row',
      description: 'The Nasdaq rallied for day number six but the rest of the market was little changed with investors torn between a jump in global novel coronavirus cases and more economies set to reopen. Conway G. Gittens has the market round-up.',
      tags: ['coronavirus', 'disneyland', 'economy', 'nasdaq', 'tech', 'under armour', 'wall street', 'walt disney'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/4\/80761184-7c8f-414a-b54c-84199e582d45.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155899798001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '11',
        provider: {
          id: '4', name: 'Reuters', legalName: 'Reuters', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/4\/f7ec6d22-dfbf-4d8e-9ad6-7d798ec38ba7.png?h=100&w=100' },
        },
      },
      genres: ['Business'],
      duration: 105,
      created: '2020-05-11T21:55:20.125135+00:00',
      modified: '2020-05-11T21:57:17.171940+00:00',
      activeSince: null,
      providerAssetId: 'tag:reuters.com,2020:newsml_OVCDHSQYZ',
    },
    {
      id: '13601',
      title: "Government decision to open schools 'premature and reckless', says head of teachers' union",
      description: "The general secretary of the NASUWT, Patrick Roach, says he has not seen a shred of evidence to suggest schools should reopen on June 1 and the Government's decision to do so is premature and reckless.",
      tags: ['coronavirus', 'decision', 'dr patrick roach', 'government', 'health', 'open', 'reckless', 'schools', 'the teachers union'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/9\/f0e2afe2-f75f-4160-ae2a-15d4807d06b1.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155900464001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '5',
        provider: {
          id: '9', name: 'Press Association', legalName: 'Press Association', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/9\/35fe0f0c-b518-4b63-92f7-e41ee2a545e0.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 92,
      created: '2020-05-11T21:37:12.249273+00:00',
      modified: '2020-05-11T21:39:09.710657+00:00',
      activeSince: null,
      providerAssetId: '78287',
    },
    {
      id: '13596',
      title: 'Boris Johnson: UK at forefront of finding Covid-19 vaccine',
      description: 'Prime Minister Boris Johnson says the UK is at the forefront of trying to find a coronavirus vaccine but admitted this may never happen.',
      tags: ['boris johnson', 'chris whitty', 'coronavirus', 'covid 19', 'disease', 'drug', 'epidemic', 'illness', 'newseurope news', 'pandemic', 'pm', 'prime minister', 'vaccine', 'virus'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/9\/0dc1744a-2146-41ef-9209-ebd302575551.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155886020001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '5',
        provider: {
          id: '9', name: 'Press Association', legalName: 'Press Association', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/9\/35fe0f0c-b518-4b63-92f7-e41ee2a545e0.png?h=100&w=100' },
        },
      },
      genres: ['News'],
      duration: 101,
      created: '2020-05-11T20:37:09.546770+00:00',
      modified: '2020-05-11T20:38:39.943234+00:00',
      activeSince: null,
      providerAssetId: '78283',
    },
    {
      id: '13594',
      title: 'Twitter launches labels, warnings on misleading COVID-19 information',
      description: 'Twitter will add labels and warning messages on some tweets with disputed or misleading information about COVID-19, the company said on Monday, as part of a new approach to misinformation that will eventually extend to other topics. This report produced by Yahaira Jacquez.',
      tags: ['coronavirus', 'covid 19', 'information tweet', 'messages', 'misinformation', 'misleading', 'twitter'],
      thumbnail: { url: 'https:\/\/oovvuu-thumbnails-staging.imgix.net\/4\/6751b5fd-4ca2-416a-a280-4776e512933e.jpeg?h=281&w=500' },
      preview: { brightcoveVideoId: '6155883704001', brightcovePlayerId: 'zZm704mP', brightcoveAccountId: '5798671154001' },
      collection: {
        id: '11',
        provider: {
          id: '4', name: 'Reuters', legalName: 'Reuters', logo: { url: 'https:\/\/oovvuu-logos-staging.imgix.net\/4\/f7ec6d22-dfbf-4d8e-9ad6-7d798ec38ba7.png?h=100&w=100' },
        },
      },
      genres: ['Business'],
      duration: 71,
      created: '2020-05-11T20:14:50.524807+00:00',
      modified: '2020-05-11T20:16:38.497280+00:00',
      activeSince: null,
      providerAssetId: 'tag:reuters.com,2020:newsml_OVCDHSU4R',
    },
  ],
  positionTwoEmptyReason: null,
};

export default recommendedVideos;
